# Generated by Django 2.2.5 on 2019-10-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddPasswordModel',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
